### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by kimarre** [KimRAWR/CSTutor#1]
#### Group stuff
- [x] Package directory under `cstutor/implementation/source/java` <sup>(1)</sup>
- [x] `overview.html` <sup>(2)</sup>
- [x] Operational menubar. <sup>(5)</sup>
- [ ] `m2-duties.html` file under `administration`
- [ ]  Update `work-breakdown.html` <sup>(10)</sup>
- [ ] `HOW-TO-RUN.html` under `administration`. <sup>(11)</sup>
#### Individual Stuff
- Stubbed methods in model classes (3 per class, 6 total methods per person)
- Generated JavaDoc comments for [ALL THE THINGS](http://i.imgur.com/Wyzn1.jpg) <sup>(7)</sup>
  - Every class _must_ have `@author` <sup>(8)</sup>
- Two pairs of model/view classes for each team member <sup>(6)</sup>
- `package.html` within each package directory - describe purpose and contents of package<sup> (3)</sup>
- Derived and compatible .java files for model classes. <sup>(4)</sup>

**[Formal Spec](http://users.csc.calpoly.edu/~gfisher/classes/309/handouts/milestone2.html)**

EDIT:
- **Update all package names to reflect changes in directory structure. Package names should now begin with something like `CSTutor.View.whatever` or `CSTutor.Model.whatever`**

**Comment by kimarre** [comment]
Kay! No BS checklist for this milestone is finished. Things with checkmarks are files that we need to be sure are in our cstutor directory. Bullets are things that each of us need to be sure we have done. Parenthesis are for the number referenced from his [Milestone 2 specs](http://users.csc.calpoly.edu/~gfisher/classes/309/handouts/milestone2.html).

**Comment by kimarre** [comment]
I added another bullet under Individual Stuff. It's in bold and it's shiny and new.
